name: Netch Build CI
on: 
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build
        shell: pwsh
        run: |
          .\build.ps1 -Configuration Release -OutputPath release

      - name: Upload
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v2
        with:
          name: Netch
          path: release
